# -*- mode: ruby -*-
    # vi: set ft=ruby :
    Vagrant.configure("2") do |config|
                   config.vm.box = "precise64"
                   config.vm.hostname = "nodo1"
		   config.vm.network :private_network, ip: "10.1.1.101"
    end  
