# -*- mode: ruby -*-
    # vi: set ft=ruby :
    Vagrant.configure("2") do |config|
                   config.vm.box = "precise64"
                   config.vm.hostname = "mimaquina"
                   config.vm.network :public_network,:bridge=>"eth0"
    end  
